---
- name: Add grafana repository
  yum_repository:
    name: grafana
    description: Grafana repository
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: True
    gpgkey: 'https://packages.grafana.com/gpg.key'
    sslverify: True
    sslcacert: '/etc/pki/tls/certs/ca-bundle.crt'
    metadata_expire: 3600

- name: Install grafana
  yum:
     name: grafana
     state: present
     enablerepo: grafana